# Copyright Hunter Damron 2018

VERSION:=$(firstword $(shell cat VERSIONS.txt))
DIST_FILE:=dist/tyr-$(VERSION).tar.gz

MAN=doc/man
MAN_PAGES_GEN:=$(patsubst %.in,%,$(shell find $(MAN) -type f -name '*.in'))
MAN_PAGES:=$(MAN_PAGES_GEN) $(filter-out $(MAN_PAGES_GEN),$(shell find $(MAN) -type f ! -name '*.in'))
MAN_DEST=/usr/local/share/man/man1

DEPS:=setup.py $(wildcard tyr/*.py test/src/*.tyr)

SYNOPSIS:=$(shell ./tyrc -h | sed '2q;d' | xargs)
OPTIONS:=$(shell ./tyrc -h | tail -n+4)

PY=python3
PIP=pip3

all:  # Do nothing by default

.PHONY: test
test:
	$(PY) setup.py test
	$(MAKE) -C test/

dist: $(DIST_FILE)

$(DIST_FILE): $(DEPS)
	$(PY) setup.py sdist

install: installdoc
	$(PY) setup.py install --force

installdoc: $(MAN_PAGES)
	install -g 0 -o 0 -m 0644 $^ $(MAN_DEST)
	gzip -f $(MAN_DEST)/$(^F)

tyr/generator.py: tyr/llvm_code/stdio.ll

man: $(MAN_PAGES)
$(MAN_PAGES_GEN): %: %.in
	echo '.\" AUTOGENERATED DO NOT EDIT' > $@
	cat $< | \
	sed 's/\$$date\$$/'"$(shell date '+%d %b %Y')"'/' | \
	sed 's/\$$version\$$/'"$(VERSION)"'/' >> $@

uninstall: uninstalldoc
	$(PIP) uninstall tyr

uninstalldoc:
	$(RM) $(addprefix $(MAN_DEST)/,$(notdir $(MAN_PAGES))).gz

clean:
	find . -name '*.py[co]' -delete
	find . -name '__pycache__' -delete
	$(MAKE) -C test/ clean

distclean: clean
	rm -rf dist/ build/ tyr.egg-info/
