#! /usr/bin/env python3

# Copyright Hunter Damron 2018

"""
Usage:
  tyrc [-vd] <file> [-o <output>]
  tyrc -h

Options:
  -h           Show this help screen
  -v           Be verbose
  -d           Be extremely verbose in debug mode
  -o <output>  Specify LLVM IR output file [default: a.ll]
"""
from docopt import docopt

import tyr

if __name__ == "__main__":
  args = docopt(__doc__, version='tyrc 0.0.1')
  ifile = args['<file>']
  ofile = args['-o']
  if args['-v']:
    tyr.util.setverbosity(4)
  if args['-d']:
    tyr.util.setverbosity(5)
  tyr.compile(ifile, ofile)
